name: ESLint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ESLint
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm run eslint
